
title: Gabriel Broilo Luz
url: 'https://broilogabriel.github.io'
baseurl: 'https://broilogabriel.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Gabriel Broilo Luz
tagline: Full Stack Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: broilo.gabriel@gmail.com
phone: +353 83 819 6098
website: broilogabriel.github.io #do not add http://
linkedin: broilogabriel
github: broilogabriel
twitter: '@broilogabriel'

#Update all the sections by editing the files inside _includes folder.
